### ISSUE TITLE
README should suggest we use the SSH github url?

### ISSUE THREAD

**Issue by neo-tahi** [debops/ansible-rails_deploy#19]
I tried using the https github URL, and this caused an error.

When I used the SSH github URL, e.g. `git@github.com:Tahi-project/ihat.git`, it worked.

Should we add this to the docs?

Cheers,
@DTrejo & @Faun

**Comment by drybjed** [comment]
HTTPS shouldn't give you an error, unless you don't have `ca-certificates` installed. Can you show the error you got?

**Comment by neo-tahi** [comment]
It was a while ago that this error happened, we should have saved the message.

I think since we don't have anything concrete for you on this, we are going to close the issue.
